
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jan 12 2025 16:09:52 IST (Jan 12 2025 10:39:52 UTC)

// Verification Directory fv/decoder 

module decoder(clk, rst, i_en, i_head_flit, i_body_flit_1,
     i_body_flit_2, i_body_flit_3, i_body_flit_4, i_tail_flit, o_wdata,
     o_address, o_read_write_enable, o_en);
  input clk, rst, i_en;
  input [15:0] i_head_flit, i_body_flit_1, i_body_flit_2,
       i_body_flit_3, i_body_flit_4, i_tail_flit;
  output [31:0] o_wdata;
  output [13:0] o_address;
  output o_read_write_enable, o_en;
  wire clk, rst, i_en;
  wire [15:0] i_head_flit, i_body_flit_1, i_body_flit_2, i_body_flit_3,
       i_body_flit_4, i_tail_flit;
  wire [31:0] o_wdata;
  wire [13:0] o_address;
  wire o_read_write_enable, o_en;
  wire [1:0] r_state;
  wire [15:0] \r_buffer[3] ;
  wire [15:0] \r_buffer[2] ;
  wire [15:0] \r_buffer[1] ;
  wire [15:0] \r_buffer[4] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, r_decode_complete_flag, r_sample_complete_flag;
  DFFRHQX1 \r_state_reg[0] (.RN (n_15), .CK (clk), .D (n_17), .Q
       (r_state[0]));
  OAI211X1 g592__2398(.A0 (r_sample_complete_flag), .A1 (n_11), .B0
       (n_10), .C0 (n_13), .Y (n_17));
  SDFFQX1 \r_buffer_reg[3][10] (.CK (clk), .D (\r_buffer[3] [10]), .SI
       (i_body_flit_3[10]), .SE (n_16), .Q (\r_buffer[3] [10]));
  SDFFQX1 \r_buffer_reg[2][4] (.CK (clk), .D (\r_buffer[2] [4]), .SI
       (i_body_flit_2[4]), .SE (n_16), .Q (\r_buffer[2] [4]));
  SDFFQX1 \r_buffer_reg[2][5] (.CK (clk), .D (\r_buffer[2] [5]), .SI
       (i_body_flit_2[5]), .SE (n_16), .Q (\r_buffer[2] [5]));
  SDFFQX1 \r_buffer_reg[2][6] (.CK (clk), .D (\r_buffer[2] [6]), .SI
       (i_body_flit_2[6]), .SE (n_16), .Q (\r_buffer[2] [6]));
  SDFFQX1 \r_buffer_reg[2][8] (.CK (clk), .D (\r_buffer[2] [8]), .SI
       (i_body_flit_2[8]), .SE (n_16), .Q (\r_buffer[2] [8]));
  SDFFQX1 \r_buffer_reg[2][7] (.CK (clk), .D (\r_buffer[2] [7]), .SI
       (i_body_flit_2[7]), .SE (n_16), .Q (\r_buffer[2] [7]));
  SDFFQX1 \r_buffer_reg[2][9] (.CK (clk), .D (\r_buffer[2] [9]), .SI
       (i_body_flit_2[9]), .SE (n_16), .Q (\r_buffer[2] [9]));
  SDFFQX1 \r_buffer_reg[2][10] (.CK (clk), .D (\r_buffer[2] [10]), .SI
       (i_body_flit_2[10]), .SE (n_16), .Q (\r_buffer[2] [10]));
  SDFFQX1 \r_buffer_reg[2][11] (.CK (clk), .D (\r_buffer[2] [11]), .SI
       (i_body_flit_2[11]), .SE (n_16), .Q (\r_buffer[2] [11]));
  SDFFQX1 \r_buffer_reg[2][12] (.CK (clk), .D (\r_buffer[2] [12]), .SI
       (i_body_flit_2[12]), .SE (n_16), .Q (\r_buffer[2] [12]));
  SDFFQX1 \r_buffer_reg[2][13] (.CK (clk), .D (\r_buffer[2] [13]), .SI
       (i_body_flit_2[13]), .SE (n_16), .Q (\r_buffer[2] [13]));
  SDFFQX1 \r_buffer_reg[2][14] (.CK (clk), .D (\r_buffer[2] [14]), .SI
       (i_body_flit_2[14]), .SE (n_16), .Q (\r_buffer[2] [14]));
  SDFFQX1 \r_buffer_reg[2][15] (.CK (clk), .D (\r_buffer[2] [15]), .SI
       (i_body_flit_2[15]), .SE (n_16), .Q (\r_buffer[2] [15]));
  SDFFQX1 \r_buffer_reg[3][2] (.CK (clk), .D (\r_buffer[3] [2]), .SI
       (i_body_flit_3[2]), .SE (n_16), .Q (\r_buffer[3] [2]));
  SDFFQX1 \r_buffer_reg[3][3] (.CK (clk), .D (\r_buffer[3] [3]), .SI
       (i_body_flit_3[3]), .SE (n_16), .Q (\r_buffer[3] [3]));
  SDFFQX1 \r_buffer_reg[3][4] (.CK (clk), .D (\r_buffer[3] [4]), .SI
       (i_body_flit_3[4]), .SE (n_16), .Q (\r_buffer[3] [4]));
  SDFFQX1 \r_buffer_reg[3][5] (.CK (clk), .D (\r_buffer[3] [5]), .SI
       (i_body_flit_3[5]), .SE (n_16), .Q (\r_buffer[3] [5]));
  SDFFQX1 \r_buffer_reg[3][6] (.CK (clk), .D (\r_buffer[3] [6]), .SI
       (i_body_flit_3[6]), .SE (n_16), .Q (\r_buffer[3] [6]));
  SDFFQX1 \r_buffer_reg[3][7] (.CK (clk), .D (\r_buffer[3] [7]), .SI
       (i_body_flit_3[7]), .SE (n_16), .Q (\r_buffer[3] [7]));
  SDFFQX1 \r_buffer_reg[1][1] (.CK (clk), .D (\r_buffer[1] [1]), .SI
       (i_body_flit_1[1]), .SE (n_16), .Q (\r_buffer[1] [1]));
  SDFFQX1 \r_buffer_reg[3][8] (.CK (clk), .D (\r_buffer[3] [8]), .SI
       (i_body_flit_3[8]), .SE (n_16), .Q (\r_buffer[3] [8]));
  SDFFQX1 \r_buffer_reg[3][9] (.CK (clk), .D (\r_buffer[3] [9]), .SI
       (i_body_flit_3[9]), .SE (n_16), .Q (\r_buffer[3] [9]));
  SDFFQX1 \r_buffer_reg[3][1] (.CK (clk), .D (\r_buffer[3] [1]), .SI
       (i_body_flit_3[1]), .SE (n_16), .Q (\r_buffer[3] [1]));
  DFFRHQX1 \r_state_reg[1] (.RN (n_15), .CK (clk), .D (n_12), .Q
       (r_state[1]));
  SDFFQX1 \r_buffer_reg[1][2] (.CK (clk), .D (\r_buffer[1] [2]), .SI
       (i_body_flit_1[2]), .SE (n_16), .Q (\r_buffer[1] [2]));
  SDFFQX1 \r_buffer_reg[3][11] (.CK (clk), .D (\r_buffer[3] [11]), .SI
       (i_body_flit_3[11]), .SE (n_16), .Q (\r_buffer[3] [11]));
  SDFFQX1 \r_buffer_reg[3][12] (.CK (clk), .D (\r_buffer[3] [12]), .SI
       (i_body_flit_3[12]), .SE (n_16), .Q (\r_buffer[3] [12]));
  SDFFQX1 \r_buffer_reg[1][3] (.CK (clk), .D (\r_buffer[1] [3]), .SI
       (i_body_flit_1[3]), .SE (n_16), .Q (\r_buffer[1] [3]));
  SDFFQX1 \r_buffer_reg[3][13] (.CK (clk), .D (\r_buffer[3] [13]), .SI
       (i_body_flit_3[13]), .SE (n_16), .Q (\r_buffer[3] [13]));
  SDFFQX1 \r_buffer_reg[1][4] (.CK (clk), .D (\r_buffer[1] [4]), .SI
       (i_body_flit_1[4]), .SE (n_16), .Q (\r_buffer[1] [4]));
  SDFFQX1 \r_buffer_reg[1][5] (.CK (clk), .D (\r_buffer[1] [5]), .SI
       (i_body_flit_1[5]), .SE (n_16), .Q (\r_buffer[1] [5]));
  SDFFQX1 \r_buffer_reg[3][14] (.CK (clk), .D (\r_buffer[3] [14]), .SI
       (i_body_flit_3[14]), .SE (n_16), .Q (\r_buffer[3] [14]));
  SDFFQX1 \r_buffer_reg[1][7] (.CK (clk), .D (\r_buffer[1] [7]), .SI
       (i_body_flit_1[7]), .SE (n_16), .Q (\r_buffer[1] [7]));
  SDFFQX1 \r_buffer_reg[1][8] (.CK (clk), .D (\r_buffer[1] [8]), .SI
       (i_body_flit_1[8]), .SE (n_16), .Q (\r_buffer[1] [8]));
  SDFFQX1 \r_buffer_reg[1][9] (.CK (clk), .D (\r_buffer[1] [9]), .SI
       (i_body_flit_1[9]), .SE (n_16), .Q (\r_buffer[1] [9]));
  SDFFQX1 \r_buffer_reg[1][10] (.CK (clk), .D (\r_buffer[1] [10]), .SI
       (i_body_flit_1[10]), .SE (n_16), .Q (\r_buffer[1] [10]));
  SDFFQX1 \r_buffer_reg[1][11] (.CK (clk), .D (\r_buffer[1] [11]), .SI
       (i_body_flit_1[11]), .SE (n_16), .Q (\r_buffer[1] [11]));
  SDFFQX1 \r_buffer_reg[1][12] (.CK (clk), .D (\r_buffer[1] [12]), .SI
       (i_body_flit_1[12]), .SE (n_16), .Q (\r_buffer[1] [12]));
  SDFFQX1 \r_buffer_reg[1][13] (.CK (clk), .D (\r_buffer[1] [13]), .SI
       (i_body_flit_1[13]), .SE (n_16), .Q (\r_buffer[1] [13]));
  SDFFQX1 \r_buffer_reg[1][6] (.CK (clk), .D (\r_buffer[1] [6]), .SI
       (i_body_flit_1[6]), .SE (n_16), .Q (\r_buffer[1] [6]));
  SDFFQX1 \r_buffer_reg[1][14] (.CK (clk), .D (\r_buffer[1] [14]), .SI
       (i_body_flit_1[14]), .SE (n_16), .Q (\r_buffer[1] [14]));
  SDFFQX1 \r_buffer_reg[1][15] (.CK (clk), .D (\r_buffer[1] [15]), .SI
       (i_body_flit_1[15]), .SE (n_16), .Q (\r_buffer[1] [15]));
  SDFFQX1 \r_buffer_reg[2][1] (.CK (clk), .D (\r_buffer[2] [1]), .SI
       (i_body_flit_2[1]), .SE (n_16), .Q (\r_buffer[2] [1]));
  SDFFQX1 \r_buffer_reg[2][2] (.CK (clk), .D (\r_buffer[2] [2]), .SI
       (i_body_flit_2[2]), .SE (n_16), .Q (\r_buffer[2] [2]));
  SDFFQX1 \r_buffer_reg[2][3] (.CK (clk), .D (\r_buffer[2] [3]), .SI
       (i_body_flit_2[3]), .SE (n_16), .Q (\r_buffer[2] [3]));
  SDFFQX1 \r_buffer_reg[4][15] (.CK (clk), .D (\r_buffer[4] [15]), .SI
       (i_body_flit_4[15]), .SE (n_16), .Q (\r_buffer[4] [15]));
  SDFFQX1 \r_buffer_reg[3][15] (.CK (clk), .D (\r_buffer[3] [15]), .SI
       (i_body_flit_3[15]), .SE (n_16), .Q (\r_buffer[3] [15]));
  SDFFQX1 \r_buffer_reg[4][14] (.CK (clk), .D (\r_buffer[4] [14]), .SI
       (i_body_flit_4[14]), .SE (n_16), .Q (\r_buffer[4] [14]));
  SDFFQX1 \r_address_reg[9] (.CK (clk), .D (\r_buffer[1] [11]), .SI
       (o_address[9]), .SE (n_14), .Q (o_address[9]));
  DFFQXL r_decode_complete_flag_reg(.CK (clk), .D (n_8), .Q
       (r_decode_complete_flag));
  SDFFQX1 \r_data_reg[28] (.CK (clk), .D (\r_buffer[2] [12]), .SI
       (o_wdata[28]), .SE (n_14), .Q (o_wdata[28]));
  SDFFQX1 \r_data_reg[29] (.CK (clk), .D (\r_buffer[2] [13]), .SI
       (o_wdata[29]), .SE (n_14), .Q (o_wdata[29]));
  SDFFQX1 \r_data_reg[31] (.CK (clk), .D (\r_buffer[2] [15]), .SI
       (o_wdata[31]), .SE (n_14), .Q (o_wdata[31]));
  SDFFQX1 r_rw_reg(.CK (clk), .D (\r_buffer[1] [1]), .SI
       (o_read_write_enable), .SE (n_14), .Q (o_read_write_enable));
  SDFFQX1 \r_address_reg[5] (.CK (clk), .D (\r_buffer[1] [7]), .SI
       (o_address[5]), .SE (n_14), .Q (o_address[5]));
  SDFFQX1 \r_data_reg[30] (.CK (clk), .D (\r_buffer[2] [14]), .SI
       (o_wdata[30]), .SE (n_14), .Q (o_wdata[30]));
  SDFFQX1 \r_address_reg[6] (.CK (clk), .D (\r_buffer[1] [8]), .SI
       (o_address[6]), .SE (n_14), .Q (o_address[6]));
  SDFFQX1 \r_address_reg[7] (.CK (clk), .D (\r_buffer[1] [9]), .SI
       (o_address[7]), .SE (n_14), .Q (o_address[7]));
  SDFFQX1 \r_data_reg[27] (.CK (clk), .D (\r_buffer[2] [11]), .SI
       (o_wdata[27]), .SE (n_14), .Q (o_wdata[27]));
  SDFFQX1 \r_address_reg[8] (.CK (clk), .D (\r_buffer[1] [10]), .SI
       (o_address[8]), .SE (n_14), .Q (o_address[8]));
  SDFFQX1 \r_data_reg[17] (.CK (clk), .D (\r_buffer[2] [1]), .SI
       (o_wdata[17]), .SE (n_14), .Q (o_wdata[17]));
  SDFFQX1 \r_address_reg[4] (.CK (clk), .D (\r_buffer[1] [6]), .SI
       (o_address[4]), .SE (n_14), .Q (o_address[4]));
  SDFFQX1 \r_address_reg[11] (.CK (clk), .D (\r_buffer[1] [13]), .SI
       (o_address[11]), .SE (n_14), .Q (o_address[11]));
  SDFFQX1 \r_address_reg[10] (.CK (clk), .D (\r_buffer[1] [12]), .SI
       (o_address[10]), .SE (n_14), .Q (o_address[10]));
  SDFFQX1 \r_data_reg[22] (.CK (clk), .D (\r_buffer[2] [6]), .SI
       (o_wdata[22]), .SE (n_14), .Q (o_wdata[22]));
  SDFFQX1 \r_address_reg[12] (.CK (clk), .D (\r_buffer[1] [14]), .SI
       (o_address[12]), .SE (n_14), .Q (o_address[12]));
  SDFFQX1 \r_address_reg[2] (.CK (clk), .D (\r_buffer[1] [4]), .SI
       (o_address[2]), .SE (n_14), .Q (o_address[2]));
  SDFFQX1 \r_address_reg[13] (.CK (clk), .D (\r_buffer[1] [15]), .SI
       (o_address[13]), .SE (n_14), .Q (o_address[13]));
  SDFFQX1 \r_address_reg[0] (.CK (clk), .D (\r_buffer[1] [2]), .SI
       (o_address[0]), .SE (n_14), .Q (o_address[0]));
  SDFFQX1 \r_address_reg[1] (.CK (clk), .D (\r_buffer[1] [3]), .SI
       (o_address[1]), .SE (n_14), .Q (o_address[1]));
  SDFFQX1 \r_data_reg[14] (.CK (clk), .D (\r_buffer[3] [13]), .SI
       (o_wdata[14]), .SE (n_14), .Q (o_wdata[14]));
  SDFFQX1 \r_data_reg[0] (.CK (clk), .D (\r_buffer[4] [14]), .SI
       (o_wdata[0]), .SE (n_14), .Q (o_wdata[0]));
  DFFHQX1 o_en_reg(.CK (clk), .D (n_9), .Q (o_en));
  SDFFQX1 \r_data_reg[15] (.CK (clk), .D (\r_buffer[3] [14]), .SI
       (o_wdata[15]), .SE (n_14), .Q (o_wdata[15]));
  SDFFQX1 \r_data_reg[3] (.CK (clk), .D (\r_buffer[3] [2]), .SI
       (o_wdata[3]), .SE (n_14), .Q (o_wdata[3]));
  SDFFQX1 \r_data_reg[4] (.CK (clk), .D (\r_buffer[3] [3]), .SI
       (o_wdata[4]), .SE (n_14), .Q (o_wdata[4]));
  SDFFQX1 \r_data_reg[5] (.CK (clk), .D (\r_buffer[3] [4]), .SI
       (o_wdata[5]), .SE (n_14), .Q (o_wdata[5]));
  SDFFQX1 \r_data_reg[6] (.CK (clk), .D (\r_buffer[3] [5]), .SI
       (o_wdata[6]), .SE (n_14), .Q (o_wdata[6]));
  SDFFQX1 \r_data_reg[8] (.CK (clk), .D (\r_buffer[3] [7]), .SI
       (o_wdata[8]), .SE (n_14), .Q (o_wdata[8]));
  SDFFQX1 \r_data_reg[9] (.CK (clk), .D (\r_buffer[3] [8]), .SI
       (o_wdata[9]), .SE (n_14), .Q (o_wdata[9]));
  SDFFQX1 \r_data_reg[11] (.CK (clk), .D (\r_buffer[3] [10]), .SI
       (o_wdata[11]), .SE (n_14), .Q (o_wdata[11]));
  SDFFQX1 \r_data_reg[10] (.CK (clk), .D (\r_buffer[3] [9]), .SI
       (o_wdata[10]), .SE (n_14), .Q (o_wdata[10]));
  SDFFQX1 \r_data_reg[7] (.CK (clk), .D (\r_buffer[3] [6]), .SI
       (o_wdata[7]), .SE (n_14), .Q (o_wdata[7]));
  SDFFQX1 \r_data_reg[13] (.CK (clk), .D (\r_buffer[3] [12]), .SI
       (o_wdata[13]), .SE (n_14), .Q (o_wdata[13]));
  SDFFQX1 \r_data_reg[12] (.CK (clk), .D (\r_buffer[3] [11]), .SI
       (o_wdata[12]), .SE (n_14), .Q (o_wdata[12]));
  SDFFQX1 \r_data_reg[2] (.CK (clk), .D (\r_buffer[3] [1]), .SI
       (o_wdata[2]), .SE (n_14), .Q (o_wdata[2]));
  SDFFQX1 \r_data_reg[16] (.CK (clk), .D (\r_buffer[3] [15]), .SI
       (o_wdata[16]), .SE (n_14), .Q (o_wdata[16]));
  SDFFQX1 \r_data_reg[18] (.CK (clk), .D (\r_buffer[2] [2]), .SI
       (o_wdata[18]), .SE (n_14), .Q (o_wdata[18]));
  SDFFQX1 \r_data_reg[19] (.CK (clk), .D (\r_buffer[2] [3]), .SI
       (o_wdata[19]), .SE (n_14), .Q (o_wdata[19]));
  SDFFQX1 \r_data_reg[20] (.CK (clk), .D (\r_buffer[2] [4]), .SI
       (o_wdata[20]), .SE (n_14), .Q (o_wdata[20]));
  SDFFQX1 \r_data_reg[21] (.CK (clk), .D (\r_buffer[2] [5]), .SI
       (o_wdata[21]), .SE (n_14), .Q (o_wdata[21]));
  SDFFQX1 \r_data_reg[1] (.CK (clk), .D (\r_buffer[4] [15]), .SI
       (o_wdata[1]), .SE (n_14), .Q (o_wdata[1]));
  SDFFQX1 \r_address_reg[3] (.CK (clk), .D (\r_buffer[1] [5]), .SI
       (o_address[3]), .SE (n_14), .Q (o_address[3]));
  SDFFQX1 \r_data_reg[24] (.CK (clk), .D (\r_buffer[2] [8]), .SI
       (o_wdata[24]), .SE (n_14), .Q (o_wdata[24]));
  SDFFQX1 \r_data_reg[23] (.CK (clk), .D (\r_buffer[2] [7]), .SI
       (o_wdata[23]), .SE (n_14), .Q (o_wdata[23]));
  SDFFQX1 \r_data_reg[25] (.CK (clk), .D (\r_buffer[2] [9]), .SI
       (o_wdata[25]), .SE (n_14), .Q (o_wdata[25]));
  SDFFQX1 \r_data_reg[26] (.CK (clk), .D (\r_buffer[2] [10]), .SI
       (o_wdata[26]), .SE (n_14), .Q (o_wdata[26]));
  DFFHQX1 r_sample_complete_flag_reg(.CK (clk), .D (n_7), .Q
       (r_sample_complete_flag));
  NAND2X1 g645__5107(.A (r_decode_complete_flag), .B (n_4), .Y (n_13));
  OAI211X1 g593__6260(.A0 (n_6), .A1 (n_11), .B0 (n_2), .C0 (n_14), .Y
       (n_12));
  AOI33XL g644__4319(.A0 (i_en), .A1 (n_5), .A2 (n_0), .B0
       (r_state[0]), .B1 (n_1), .B2 (r_state[1]), .Y (n_10));
  OAI2BB1X1 g643__8428(.A0N (o_en), .A1N (r_state[0]), .B0 (n_3), .Y
       (n_9));
  OAI2BB1X1 g647__5526(.A0N (r_decode_complete_flag), .A1N
       (r_state[0]), .B0 (n_14), .Y (n_8));
  OAI21XL g648__6783(.A0 (n_6), .A1 (n_5), .B0 (n_11), .Y (n_7));
  INVX1 g650(.A (n_14), .Y (n_4));
  INVX1 g651(.A (n_11), .Y (n_16));
  OAI21X1 g646__3680(.A0 (o_en), .A1 (r_state[0]), .B0 (r_state[1]), .Y
       (n_3));
  NAND2XL g649__1617(.A (n_1), .B (r_state[1]), .Y (n_2));
  NAND2X1 g653__2802(.A (r_state[0]), .B (n_5), .Y (n_11));
  OR2X1 g652__1705(.A (r_state[0]), .B (n_5), .Y (n_14));
  INVXL g654(.A (rst), .Y (n_15));
  INVX1 g656(.A (r_sample_complete_flag), .Y (n_6));
  INVXL g658(.A (r_state[0]), .Y (n_0));
  INVXL g655(.A (o_en), .Y (n_1));
  INVX1 g657(.A (r_state[1]), .Y (n_5));
endmodule

